import type { Metadata } from "next";
import { Geist } from "next/font/google";
import type { PropsWithChildren } from "react";
import "./globals.css";
<<<<<<< HEAD
import { Providers } from "@/components/shared/providers";
import { cn } from "@/lib/utils";
=======
>>>>>>> 80520a05d9b7d0ad5a74341d6f121a796f7fd8d4

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
<<<<<<< HEAD
		<html lang="en" suppressHydrationWarning>
			<body className={cn(geistSans.variable)}>
				<Providers>{children}</Providers>
			</body>
=======
		<html lang="en">
			<body className={geistSans.variable}>{children}</body>
>>>>>>> 80520a05d9b7d0ad5a74341d6f121a796f7fd8d4
		</html>
	);
}
